//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Created { get; set; }
        public string Amount { get; set; }
        public string Sum { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Agent Provider { get; set; }
        public virtual Agent Customer { get; set; }
    }
}
