//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogExample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogItem
    {
        public BlogItem()
        {
            this.TagToBlog = new HashSet<TagToBlog>();
            this.AuthorToBlog = new HashSet<AuthorToBlog>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Context { get; set; }
    
        public virtual ICollection<TagToBlog> TagToBlog { get; set; }
        public virtual ICollection<AuthorToBlog> AuthorToBlog { get; set; }
    }
}
